Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"


  config.vm.network "public_network", ip: "192.168.1.57"
  config.vm.synced_folder "../ansible/", "/tmp/ansible"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt -y install ansible
    sudo ansible-playbook /tmp/ansible/playbook-zabbix.yml
    SHELL

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end        
end  
