---
- name: Unarchive create.sql.gz
  command: gunzip /usr/share/doc/zabbix-sql-scripts/mysql/server.sql.gz
  ignore_errors: yes
  
- name: Create database zabbix
  mysql_db:
    login_host: "{{ DBHost_address }}"
    login_password: "{{ login_mysql_password }}"
    login_user: "{{ login_mysql_user }}"
    name: "{{ DBName }}"
    encoding: utf8
    collation: utf8_bin  
  register: db_created    

- name: Create user zabbix
  mysql_user:
    login_host: "{{ DBHost_address }}"
    login_password: "{{ login_mysql_password }}"
    login_user: "{{ login_mysql_user }}"
    name: "{{ DBUser }}"
    password: "{{ DBPassword }}"
    priv: '*.*:ALL'
    state: present
    host: "{{ item }}"
  with_items:
    - "{{ zabbix_server_address }}"
    - "{{ zabbix_frontend_address }}"
    - "{{ DBHost_address }}"

- name: Import schema and data
  mysql_db:
    state: import
    login_host: "{{ DBHost_address }}"
    login_password: "{{ DBPassword }}"
    login_user: "{{ DBUser }}"
    name: "{{ DBName }}"
    encoding: utf8
    collation: utf8_bin
    target: /usr/share/doc/zabbix-sql-scripts/mysql/server.sql
  when: db_created.changed  
 
- name: copy template zabbix_server.conf
  template:
    dest: /etc/zabbix
    src: zabbix_server.conf

- name: copy template zabbix.conf.php
  template:
    dest: /etc/zabbix/web/zabbix.conf.php
    src: zabbix.conf.php.j2 

- name: Start service apache2
  service:
      name: apache2
      enabled: yes
      state: restarted

- name: Start service zabbix-server
  service:
      name: zabbix-server
      enabled: yes
      state: restarted
...