---
- name: Download repo zabbix
  get_url:
    url: https://repo.zabbix.com/zabbix/6.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.2-1+ubuntu20.04_all.deb
    dest: /tmp/zabbix-release_6.2-1+ubuntu20.04_all.deb

- name: Install repo zabbix
  apt:
    deb: /tmp/zabbix-release_6.2-1+ubuntu20.04_all.deb
    state: present
  ignore_errors: True 

- name: Update repo
  apt:
    update_cache: yes

- name: Install packages
  apt:
    name: 
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-agent
    state: latest    
...
